name: flutterwave_momo_ghana
description: Your users can pay you using MOMO in Ghana within your flutter app. It uses Flutterwave API.
version: 1.0.1
homepage: https://github.com/qclaire/flutterwave_momo_gh

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  webview_flutter: ^0.3.22+1
  uuid: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
